name: 05 - 2 - Event Filters and Activity Types

on:
    workflow_dispatch:

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo "Running whenever a PR is close"