name: 08 - Using Variables

on:
    push:
        branches:
            - main

    workflow_dispatch:

env:
    WORKFLOW_VAR: "I am workflow env variable"
    OVERWRITTEN: "I will be overwritten"

jobs:
   echo:
        runs-on: ubuntu-latest
        env:
            JOB_VAR: "I am job env variable"
            OVERWRITTEN: "I am overwritten by job"

        steps:
            - name: "Print Env Variables"
              env:
                STEP_VAR: "I am step env variable"
                step_var2: "I am another step variable"
              run: |
                echo "Step env var: $STEP_VAR"
                echo "Step env var 2: $step_var2"
                echo "Job env var: ${{env.JOB_VAR}}"
                echo "Workflow env var: ${{env.WORKFLOW_VAR}}"
                echo "Overwritten: ${{env.OVERWRITTEN}}"
            - name: "Overwrite Job Variable"
              env:
                OVERWRITTEN: "I have been overwritten at the step level"
              run: |
                echo "Overwritten: ${{env.OVERWRITTEN}}"
