name: 09 - Using Functions

on:
    workflow_dispatch:

    pull_request:
        branches:
            - main

    push:
        branches:
            - main


jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: "Sleep for 20 seconds"
              run: |
                echo "Sleeping for 20 seconds"
                sleep 20

            - name: "Failling Step"
              run: |
                    echo "This step will fail"
                    exit 1

            - name: "I will be skipped"
              if: ${{ success() }}
              run: |
                  echo  "I will print if previous steps succeed."

            - name: "I will execute"
              if: ${{ failure() }}
              run: |
                  echo "I will print if any previous steps fails."

            - name: "I will execute"
              if: ${{ !cancelled() }}
              run: |
                  echo "I will always print, except when the workflow is cancelled."

            - name: "I will execute when cancelled"
              if: ${{ cancelled() }}
              run: |
                  echo "I will only print when the workflow is cancelled."

