name: 10 - Controlling the Execution Flow

on:
    workflow_dispatch:
        inputs:
            pass-unit-tests:
                type: boolean
                description: "boolean that says if the unit tests passed"
                required: true
                default: false

jobs:
    lint-build:
        runs-on: ubuntu-latest
        steps:
            - name: "Lint and build"
              run: |
                echo "Linting and building project"
    unit-tests:
        runs-on: ubuntu-latest
        #continue-on-error: true
        steps:
            - name: "Running unit tests"
              run: |
                echo "Running tests..."
            - name: "Failing tests"
              if: ${{ github.event.inputs.pass-unit-tests != true }}
              run: |
                echo "Failing tests..."
                exit 1
    deploy-nonprod:
        runs-on: ubuntu-latest
        needs: [unit-tests, lint-build]
        steps:
            - name: "Deploying to nonprod"
              run: |
                echo "Deploying to nonprod..."

    e2e-tests:
        runs-on: ubuntu-latest
        needs: deploy-nonprod
        steps:
            - name: "Running E2E tests"
              run: |
                echo "Running E2E tests..."

    load-tests:
        runs-on: ubuntu-latest
        needs: deploy-nonprod
        steps:
            - name: "Running Load tests"
              run: |
                echo "Running Load tests..."

    deploy-prod:
        runs-on: ubuntu-latest
        needs: [e2e-tests, load-tests]
        steps:
            - name: "Deploying to prod"
              run: |
                echo "Deploying to prod..."

